excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - foodieTests
  - foodieUITests
disabled_rules:
  - function_body_length
  - file_length
  - type_name
  - identifier_name
  - trailing_whitespace
  - cyclomatic_complexity
  - empty_enum_arguments
  - todo
  - function_parameter_count
<<<<<<< HEAD
  - line_length
=======
>>>>>>> f26ce630a15b12d8e8b9ee68ea99d23a8b2046b7
