platform :ios, '10.0'
use_frameworks!

target 'foodie' do
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftLint', '~> 0.25'
  pod 'UIFontComplete', '~> 3.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'DKImagePickerController', '~> 4.1'
  pod 'TextFieldEffects', '~> 1.4'
  pod 'Validator', '~> 3.0'
  pod 'AWSMobileClient', '~> 2.6.13'
  pod 'AWSS3', '~> 2.6.13'
  pod 'FBSDKLoginKit'
  pod 'SwiftyUserDefaults', '4.0.0-alpha.1'
  pod 'DropDown', '~>2.3'
end
