platform :ios, '10.0'
use_frameworks!

target 'foodie' do
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftLint', '~> 0.25'
  pod 'UIFontComplete', '~> 3.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'DKImagePickerController', '~> 3.8'
  pod 'TextFieldEffects', '~> 3.0'
  pod 'Validator', '~> 3.0'
end
