platform :ios, '10.0'
use_frameworks!

target 'foodie' do
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftLint', '~> 0.25'
  pod 'UIFontComplete', '~> 3.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'DKImagePickerController', '~> 4.1'
  pod 'TextFieldEffects', '~> 1.4'
  pod 'Validator', '~> 3.0'
  pod 'FBSDKLoginKit', '~> 4.40.0'
  pod 'SwiftyUserDefaults', '4.0.0-alpha.1'
  pod 'DropDown', '~>2.3'
  pod 'ActiveLabel', '~>1.0'
  pod 'GradientLoadingBar'
  pod 'ImageSlideshow/SDWebImage'

  pod 'AWSFacebookSignIn', '~> 2.8.0'     # Add this new dependency
  pod 'AWSAuthUI', '~> 2.8.0'             # Add this dependency if you have not already added
  pod 'AWSMobileClient', '~> 2.8.0'
  pod 'AWSUserPoolsSignIn', '~> 2.8.0'
  pod 'AWSS3', '~> 2.8.0'
  
  pod 'Fabric'
  pod 'Crashlytics'
end
